/**
 * Note！ These codes are from third parties. Not currently reviewed by the community.
 * Please do not refer to the format specifications of these codes.
 */
/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        QH_HDISPLAY_CATEGORY: 'QH HDisplay',
        qdp_display_START: ' %1 Display start P5(R0-L1)',
        qdp_display_button: 'Display key P5(R0-L1)= %1',
        qdp_display_variable: 'Display variable P5(R0-L1) %1',
        qdp_display_print: 'Send variable to display P5(R0-L1)V %1 Value %2',
        qdp_zkpdisplay_sleep: 'Screen Sleep Port P5 %1',
        QH_displaysleep1: 'Sleep',
        QH_displaysleep0: 'Wakeup',
        qdp_zkpdisplay_buzzer: 'Screen buzzer Port P5 frequency %1 Volume(0-100) %2',
        qdp_zkpdisplay_clscolor: 'Brush color screen Port P5 Color %1',
        qdp_zkpdisplay_color: 'Color %1',
        qdp_zkpdisplay_pic: 'Face brush Port P5 %1',
        QH_displaypic1: 'love',
        QH_displaypic2: 'surprised',
        QH_displaypic3: 'sad',
        QH_displaypic4: 'Over your face',
        QH_displaypic5: 'Smiling face',
        QH_displaypic6: 'dizzy',
        QH_displaypic7: 'Blink of an eye',
        QH_displaypic8: 'praise',
        QH_displaypic9: 'Learn the qr code',
        qdp_zkpdisplay_page: 'Page jump Port P5 %1',
        QH_displaypage1: 'Menu',
        QH_displaypage2: 'Remote control/slider',
        QH_displaypage3: 'Remote control/variable',
        QH_displaypage4: 'Slider',
        QH_displaypage5: 'Variable',
        QH_displaypage6: 'Keys',
        QH_displaypage7: 'Serial',
        QH_displaypage8: 'The random number',
        QH_displaypage9: 'blank pages',
        qdp_zkpdisplay_drawinground: 'Circle Port P5 Type %1 X %2 Y %3 R %4 Decimal color %5',
        QH_displaysolidround: 'Solid round',
        QH_displayhollowround: 'The hollow circle',
        qdp_zkpdisplay_function1: 'Draw Port P5 Type %1 X %2 Y %3 X2W %4 Y2H %5 Decimal color %6',
        QH_displayfunction1fill: 'Area filling',
        QH_displayfunction1line: 'Line drawing',
        QH_displayfunction1draw: 'Draw a rectangular',
        qdp_zkpdisplay_TEXT: 'TEXT message Port P5 fill %1 X %2 Y %3 W %4 H %5 Text color %6 Background color %7 Content %8',
        QH_displaybackcolor0: 'Cut the figure',
        QH_displaybackcolor1: 'monochromatic',
        QH_displaybackcolor2: 'picture',
        QH_displaybackcolor3: 'No background',
        qdp_zkpdisplay_TEXT_CN: 'TEXT message Port P5 fill %1 X %2 Y %3 W %4 H %5 Text color %6 Background color %7 Content %8',
        qdp_zkpdisplay_order: 'Custom instruction Port P5 %1',
        QH_DISPLAY_MATRIX_ROTATE: 'ROTATE ',
        QH_MIRROR: 'MIRROR',
        oled_init: 'Initialization OLED %1 Name %2 Rotation angle %3 SCL %4 SDA %5 Device address %6',
        oled_page: '%1 OLED %2 Refresh the page',
        oled_showBitmap: 'OLED %1 Display image Start point X %2 Y %3 Width %4 Height %5 Image name %6',
        tool_modulus: 'Bitmap format %1 Mode %2 Direction %3 Font %4 Size %5 px Width %6 px Height %7 px Content %8',
        tool_modulus_show: 'Image name %1 [%2] save to flash %3 %4',
        oled_clear: 'OLED %1 Clear screen ',
        u8g2_setContrast: 'OLED %1 Backlight brightness %2',
        oled_face: 'OLED %1 Display image Start point X %2 Y %3 Built-in ICONS %4',
        oled_drawPixel: 'OLED %1 Draw point Start point X %2 Y %3 ',
        oled_drawLine: 'OLED %1 Draw line Start point X %2 Y %3 End point X %4 Y %5',
        oled_draw_Str_Line: 'OLED %1 Draw straight line Start point X %2 Y %3 Length X %4 Mode %5',
        QH_OLED_HOR: 'Horizontal',
        QH_OLED_VER: 'Vertical',
        oled_drawFrame: 'OLED %1 Draw rect Mode %2 Start poin X %3 Y %4 Width  %5 Height %6',
        oled_drawRFrame: 'OLED %1 Draw rect Mode %2 Start poin X %3 Y %4 Width  %5 Height %6 Radius %7',
        oled_drawCircle: 'OLED %1 Circle Mode %2 Center X %3 Y %4 Radius %5 Type %6',
        QH_OLED_WHOLE_CICILE: 'Full circle',
        QH_OLED_UP_R: 'Upper right',
        QH_OLED_UP_L: 'Upper left',
        QH_OLED_LOW_R: 'Down right',
        QH_OLED_LOW_L: 'Down left',
        oled_drawEllipse: 'OLED %1 Draw Ellipse Mode %2 Center X %3 Y %4 Radius X %5 Y %6 Type %7',
        QH_OLED_HOLLOW: 'Hollow',
        QH_OLED_SOLID: 'Solid',
        oled_drawTriangle: 'OLED %1 Draw Triangle A point X %2 Y %3 B point X %4 Y %5 C point X %6 Y %7'

    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        QH_HDISPLAY_CATEGORY: '掌控屏',
        qdp_display_START: ' %1 启用接收屏数据 P5(R0-L1)',
        qdp_display_button: '屏按钮 P5(R0-L1)= %1',
        qdp_display_variable: '屏变量 P5(R0-L1) %1',
        qdp_display_print: '发送变量到屏 P5(R0-L1)V %1 值 %2',
        qdp_zkpdisplay_sleep: '屏睡眠 端口 P5 %1',
        QH_displaysleep1: '睡眠',
        QH_displaysleep0: '唤醒',
        qdp_zkpdisplay_buzzer: '屏蜂鸣器 端口 P5 频率 %1 音量(0-100) %2',
        qdp_zkpdisplay_clscolor: '颜色刷屏 端口 P5 颜色 %1',
        qdp_zkpdisplay_color: '颜色 %1',
        qdp_zkpdisplay_pic: '表情刷屏 端口 P5 %1',
        QH_displaypic1: '爱心',
        QH_displaypic2: '惊讶',
        QH_displaypic3: '伤心',
        QH_displaypic4: '捂脸',
        QH_displaypic5: '笑脸',
        QH_displaypic6: '晕',
        QH_displaypic7: '眨眼',
        QH_displaypic8: '赞',
        QH_displaypic9: '学习二维码',
        qdp_zkpdisplay_page: '页面跳转 端口 P5 %1',
        QH_displaypage1: '主菜单',
        QH_displaypage2: '遥控/滑块',
        QH_displaypage3: '遥控/变量',
        QH_displaypage4: '滑块',
        QH_displaypage5: '变量V',
        QH_displaypage6: '按键',
        QH_displaypage7: '串口',
        QH_displaypage8: '随机数',
        QH_displaypage9: '空白页',
        qdp_zkpdisplay_drawinground: '画圆 端口 P5 类型 %1 X %2 Y %3 R %4 十进制颜色 %5',
        QH_displaysolidround: '实心圆',
        QH_displayhollowround: '空心圆',
        qdp_zkpdisplay_function1: '画图 端口 P5 类型 %1 X %2 Y %3 X2W %4 Y2H %5 十进制颜色 %6',
        QH_displayfunction1fill: '区域填充',
        QH_displayfunction1line: '画线',
        QH_displayfunction1draw: '画矩形',
        qdp_zkpdisplay_TEXT: '文字信息 端口 P5 填充 %1 X %2 Y %3 W %4 H %5 文字颜色 %6 背景颜色 %7 内容 %8',
        QH_displaybackcolor0: '切图',
        QH_displaybackcolor1: '单色',
        QH_displaybackcolor2: '图片',
        QH_displaybackcolor3: '无背景',
        qdp_zkpdisplay_TEXT_CN: '文字信息 端口 P5 填充 %1 X %2 Y %3 W %4 H %5 文字颜色 %6 背景颜色 %7 内容 %8',
        qdp_zkpdisplay_order: '自定义指令 端口 P5 %1',
        QH_DISPLAY_MATRIX_ROTATE: '旋转',
        QH_MIRROR: '镜像',
        oled_init: '初始化OLED %1 名称 %2 旋转角度 %3 SCL %4 SDA %5 设备地址 %6',
        oled_page: '%1 OLED %2 刷新页面',
        oled_showBitmap: 'OLED %1 显示图像 起点 X %2 Y %3 宽度 %4 高度 %5 图像名称 %6',
        tool_modulus: '点阵格式 %1 取模方式 %2 取模走向 %3 字体 %4 字号 %5 px 宽 %6 px 高 %7 px 内容 %8',
        tool_modulus_show: '图像名称 %1 [%2] 保存到 flash %3 %4',
        oled_clear: 'OLED %1 清屏 ',
        u8g2_setContrast: 'OLED %1 背光亮度 %2',
        oled_face: 'OLED %1 显示图像 起点 X %2 Y %3 内置图标 %4',
        oled_drawPixel: 'OLED %1 画点 起点 X %2 Y %3 ',
        oled_drawLine: 'OLED %1 画线 起点 X %2 Y %3 终点 X %4 Y %5',
        oled_draw_Str_Line: 'OLED %1 画直线 起点 X %2 Y %3 长度 X %4 模式 %5',
        QH_OLED_HOR: '水平',
        QH_OLED_VER: '垂直',
        oled_drawFrame: 'OLED %1 画矩形 模式 %2 起点 X %3 Y %4 宽  %5 高 %6',
        oled_drawRFrame: 'OLED %1 画圆角矩形 模式 %2 起点 X %3 Y %4 宽  %5 高 %6 半径 %7',
        oled_drawCircle: 'OLED %1 画圆 模式 %2 圆心 X %3 Y %4 半径  %5 类型 %6',
        QH_OLED_WHOLE_CICILE: '整圆',
        QH_OLED_UP_R: '右上',
        QH_OLED_UP_L: '左上',
        QH_OLED_LOW_R: '右下',
        QH_OLED_LOW_L: '左下',
        oled_drawEllipse: 'OLED %1 画椭圆 模式 %2 圆心 X %3 Y %4 半径 X %5 Y %6 类型 %7',
        QH_OLED_HOLLOW: '空心',
        QH_OLED_SOLID: '实心',
        oled_drawTriangle: 'OLED %1 画三角形 A点 X %2 Y %3 B点 X %4 Y %5 C点 X %6 Y %7'
    });
    return Blockly;
}

exports = addMsg;
